// <auto-generated />
using System;
using EnglishVocab.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishVocab.Infrastructure.Migrations
{
    [DbContext(typeof(EnglishVocabDatabaseContext))]
    partial class EnglishVocabDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnglishVocab.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.DifficultyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DifficultyLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 7, 13, 5, 2, 23, 267, DateTimeKind.Local).AddTicks(6907),
                            DateModified = new DateTime(2025, 7, 13, 5, 2, 23, 268, DateTimeKind.Local).AddTicks(7737),
                            Description = "Words that are commonly used in everyday conversations",
                            ModifiedBy = "System",
                            Name = "Easy",
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 7, 13, 5, 2, 23, 268, DateTimeKind.Local).AddTicks(8052),
                            DateModified = new DateTime(2025, 7, 13, 5, 2, 23, 268, DateTimeKind.Local).AddTicks(8055),
                            Description = "Words that are used in general contexts but less frequently",
                            ModifiedBy = "System",
                            Name = "Medium",
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 7, 13, 5, 2, 23, 268, DateTimeKind.Local).AddTicks(8058),
                            DateModified = new DateTime(2025, 7, 13, 5, 2, 23, 268, DateTimeKind.Local).AddTicks(8059),
                            Description = "Words that are specialized or rarely used in everyday language",
                            ModifiedBy = "System",
                            Name = "Hard",
                            Value = 3
                        });
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RedirectUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.StudySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncorrectAnswers")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.Property<bool>("ShuffleWords")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudyMode")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WordSetId")
                        .HasColumnType("int");

                    b.Property<int>("WordsKnown")
                        .HasColumnType("int");

                    b.Property<int>("WordsSkipped")
                        .HasColumnType("int");

                    b.Property<int>("WordsStudied")
                        .HasColumnType("int");

                    b.Property<int>("WordsUnknown")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WordSetId");

                    b.ToTable("StudySessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswers = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 7, 13, 5, 2, 23, 273, DateTimeKind.Local).AddTicks(9465),
                            DateModified = new DateTime(2025, 7, 13, 5, 2, 23, 273, DateTimeKind.Local).AddTicks(9470),
                            EndTime = new DateTime(2025, 7, 13, 4, 32, 23, 273, DateTimeKind.Local).AddTicks(7810),
                            IncorrectAnswers = 3,
                            ModifiedBy = "System",
                            PointsEarned = 0,
                            ShuffleWords = false,
                            StartTime = new DateTime(2025, 7, 13, 4, 2, 23, 273, DateTimeKind.Local).AddTicks(7810),
                            Status = "active",
                            StudyMode = 0,
                            UserId = "1",
                            WordSetId = 1,
                            WordsKnown = 0,
                            WordsSkipped = 0,
                            WordsStudied = 10,
                            WordsUnknown = 0
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswers = 12,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 7, 13, 5, 2, 23, 273, DateTimeKind.Local).AddTicks(9490),
                            DateModified = new DateTime(2025, 7, 13, 5, 2, 23, 273, DateTimeKind.Local).AddTicks(9611),
                            EndTime = new DateTime(2025, 7, 12, 5, 47, 23, 273, DateTimeKind.Local).AddTicks(7810),
                            IncorrectAnswers = 3,
                            ModifiedBy = "System",
                            PointsEarned = 0,
                            ShuffleWords = false,
                            StartTime = new DateTime(2025, 7, 12, 5, 2, 23, 273, DateTimeKind.Local).AddTicks(7810),
                            Status = "active",
                            StudyMode = 4,
                            UserId = "1",
                            WordSetId = 2,
                            WordsKnown = 0,
                            WordsSkipped = 0,
                            WordsStudied = 15,
                            WordsUnknown = 0
                        });
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.UserAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("int");

                    b.Property<int?>("StudySessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("WordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudySessionId");

                    b.HasIndex("WordId");

                    b.ToTable("UserActions");
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("EaseFactorInPercentage")
                        .HasColumnType("int");

                    b.Property<int>("IncorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("IntervalInDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastReviewed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MasteryLevel")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NextReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RepetitionCount")
                        .HasColumnType("int");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("TimesReviewed")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.HasIndex("UserId", "WordId")
                        .IsUnique();

                    b.ToTable("UserProgresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectCount = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 7, 13, 5, 2, 23, 277, DateTimeKind.Local).AddTicks(7130),
                            DateModified = new DateTime(2025, 7, 13, 5, 2, 23, 277, DateTimeKind.Local).AddTicks(7134),
                            EaseFactorInPercentage = 250,
                            IncorrectCount = 1,
                            IntervalInDays = 0,
                            LastReviewed = new DateTime(2025, 7, 12, 5, 2, 23, 277, DateTimeKind.Local).AddTicks(4994),
                            LastReviewedAt = new DateTime(2025, 7, 12, 22, 2, 23, 277, DateTimeKind.Utc).AddTicks(6063),
                            MasteryLevel = 1,
                            ModifiedBy = "System",
                            NextReviewDate = new DateTime(2025, 7, 14, 5, 2, 23, 277, DateTimeKind.Local).AddTicks(4994),
                            RepetitionCount = 0,
                            ReviewCount = 0,
                            TimesReviewed = 0,
                            UserId = "1",
                            WordId = 1
                        },
                        new
                        {
                            Id = 2,
                            CorrectCount = 0,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 7, 13, 5, 2, 23, 277, DateTimeKind.Local).AddTicks(7141),
                            DateModified = new DateTime(2025, 7, 13, 5, 2, 23, 277, DateTimeKind.Local).AddTicks(7142),
                            EaseFactorInPercentage = 250,
                            IncorrectCount = 0,
                            IntervalInDays = 0,
                            LastReviewed = new DateTime(2025, 7, 12, 22, 2, 23, 277, DateTimeKind.Utc).AddTicks(7138),
                            LastReviewedAt = new DateTime(2025, 7, 12, 22, 2, 23, 277, DateTimeKind.Utc).AddTicks(7139),
                            MasteryLevel = -1,
                            ModifiedBy = "System",
                            NextReviewDate = new DateTime(2025, 7, 13, 5, 2, 23, 277, DateTimeKind.Local).AddTicks(4994),
                            RepetitionCount = 0,
                            ReviewCount = 0,
                            TimesReviewed = 0,
                            UserId = "1",
                            WordId = 2
                        });
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.UserStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastStudyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LearningWords")
                        .HasColumnType("int");

                    b.Property<int>("LongestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MasteredWords")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreakDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("StreakUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int>("TotalSessions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalTimeSpent")
                        .HasColumnType("int");

                    b.Property<int>("TotalTimeSpentMinutes")
                        .HasColumnType("int");

                    b.Property<int>("TotalWordsLearned")
                        .HasColumnType("int");

                    b.Property<int>("TotalWordsStudied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStatistics");
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<int?>("DifficultyLevelId")
                        .HasColumnType("int");

                    b.Property<string>("English")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExampleTranslation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Pronunciation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Vietnamese")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DifficultyLevelId");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AudioUrl = "/audio/hello.mp3",
                            Category = "Greetings",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 7, 13, 5, 2, 23, 285, DateTimeKind.Local).AddTicks(9326),
                            DateModified = new DateTime(2025, 7, 13, 5, 2, 23, 285, DateTimeKind.Local).AddTicks(9331),
                            DifficultyLevel = 0,
                            English = "Hello",
                            Example = "Hello, how are you today?",
                            ExampleTranslation = "Xin chào, hôm nay bạn khỏe không?",
                            Frequency = 0,
                            ImageUrl = "/images/hello.jpg",
                            ModifiedBy = "System",
                            Notes = "Common greeting",
                            Pronunciation = "həˈloʊ",
                            Vietnamese = "Xin chào"
                        },
                        new
                        {
                            Id = 2,
                            AudioUrl = "/audio/goodbye.mp3",
                            Category = "Greetings",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 7, 13, 5, 2, 23, 285, DateTimeKind.Local).AddTicks(9337),
                            DateModified = new DateTime(2025, 7, 13, 5, 2, 23, 285, DateTimeKind.Local).AddTicks(9338),
                            DifficultyLevel = 0,
                            English = "Goodbye",
                            Example = "Goodbye, see you tomorrow!",
                            ExampleTranslation = "Tạm biệt, hẹn gặp lại ngày mai!",
                            Frequency = 0,
                            ImageUrl = "/images/goodbye.jpg",
                            ModifiedBy = "System",
                            Notes = "Common farewell",
                            Pronunciation = "ɡʊdˈbaɪ",
                            Vietnamese = "Tạm biệt"
                        },
                        new
                        {
                            Id = 3,
                            AudioUrl = "/audio/thankyou.mp3",
                            Category = "Expressions",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 7, 13, 5, 2, 23, 285, DateTimeKind.Local).AddTicks(9341),
                            DateModified = new DateTime(2025, 7, 13, 5, 2, 23, 285, DateTimeKind.Local).AddTicks(9342),
                            DifficultyLevel = 0,
                            English = "Thank you",
                            Example = "Thank you for your help.",
                            ExampleTranslation = "Cảm ơn vì sự giúp đỡ của bạn.",
                            Frequency = 0,
                            ImageUrl = "/images/thankyou.jpg",
                            ModifiedBy = "System",
                            Notes = "Common expression of gratitude",
                            Pronunciation = "θæŋk ju",
                            Vietnamese = "Cảm ơn"
                        });
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.WordSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WordSets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Beginner",
                            CreatedBy = "System",
                            CreatedByUserId = "1",
                            DateCreated = new DateTime(2025, 7, 13, 5, 2, 23, 286, DateTimeKind.Local).AddTicks(6341),
                            DateModified = new DateTime(2025, 7, 13, 5, 2, 23, 286, DateTimeKind.Local).AddTicks(6346),
                            Description = "Essential greetings and phrases for beginners",
                            ImageUrl = "/images/wordsets/greetings.jpg",
                            IsDefault = false,
                            IsPublic = true,
                            ModifiedBy = "System",
                            Name = "Greetings and Basic Phrases",
                            WordCount = 3
                        },
                        new
                        {
                            Id = 2,
                            Category = "Intermediate",
                            CreatedBy = "System",
                            CreatedByUserId = "1",
                            DateCreated = new DateTime(2025, 7, 13, 5, 2, 23, 286, DateTimeKind.Local).AddTicks(6351),
                            DateModified = new DateTime(2025, 7, 13, 5, 2, 23, 286, DateTimeKind.Local).AddTicks(6352),
                            Description = "Vocabulary related to food, restaurants, and dining",
                            ImageUrl = "/images/wordsets/food.jpg",
                            IsDefault = false,
                            IsPublic = true,
                            ModifiedBy = "System",
                            Name = "Food and Dining",
                            WordCount = 0
                        });
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.WordSetWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.Property<int>("WordSetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.HasIndex("WordSetId");

                    b.ToTable("WordSetWords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedDate = new DateTime(2025, 7, 13, 5, 2, 23, 288, DateTimeKind.Local).AddTicks(7275),
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 7, 13, 5, 2, 23, 288, DateTimeKind.Local).AddTicks(7408),
                            DateModified = new DateTime(2025, 7, 13, 5, 2, 23, 288, DateTimeKind.Local).AddTicks(7409),
                            ModifiedBy = "System",
                            WordId = 1,
                            WordSetId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddedDate = new DateTime(2025, 7, 13, 5, 2, 23, 288, DateTimeKind.Local).AddTicks(7413),
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 7, 13, 5, 2, 23, 288, DateTimeKind.Local).AddTicks(7414),
                            DateModified = new DateTime(2025, 7, 13, 5, 2, 23, 288, DateTimeKind.Local).AddTicks(7415),
                            ModifiedBy = "System",
                            WordId = 2,
                            WordSetId = 1
                        },
                        new
                        {
                            Id = 3,
                            AddedDate = new DateTime(2025, 7, 13, 5, 2, 23, 288, DateTimeKind.Local).AddTicks(7416),
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 7, 13, 5, 2, 23, 288, DateTimeKind.Local).AddTicks(7417),
                            DateModified = new DateTime(2025, 7, 13, 5, 2, 23, 288, DateTimeKind.Local).AddTicks(7418),
                            ModifiedBy = "System",
                            WordId = 3,
                            WordSetId = 1
                        });
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.StudySession", b =>
                {
                    b.HasOne("EnglishVocab.Domain.Entities.WordSet", null)
                        .WithMany()
                        .HasForeignKey("WordSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.UserAction", b =>
                {
                    b.HasOne("EnglishVocab.Domain.Entities.StudySession", null)
                        .WithMany()
                        .HasForeignKey("StudySessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EnglishVocab.Domain.Entities.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.UserProgress", b =>
                {
                    b.HasOne("EnglishVocab.Domain.Entities.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.Word", b =>
                {
                    b.HasOne("EnglishVocab.Domain.Entities.Category", "CategoryEntity")
                        .WithMany("Words")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EnglishVocab.Domain.Entities.DifficultyLevel", null)
                        .WithMany("Words")
                        .HasForeignKey("DifficultyLevelId");

                    b.Navigation("CategoryEntity");
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.WordSetWord", b =>
                {
                    b.HasOne("EnglishVocab.Domain.Entities.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishVocab.Domain.Entities.WordSet", "WordSet")
                        .WithMany()
                        .HasForeignKey("WordSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");

                    b.Navigation("WordSet");
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.Category", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("EnglishVocab.Domain.Entities.DifficultyLevel", b =>
                {
                    b.Navigation("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
